### ISSUE TITLE
issues with 0.3.2 and 0.3.3

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#296]
**Describe the bug**

**To Reproduce**

Odd I didn't encounter this locally, but came across this error after release:

```
{"level":"info","ts":1623018834281,"msg":"starting server","protocol":"http","bind":"0.0.0.0:8080","tls":false}
{"level":"info","ts":1623018834284,"msg":"starting server","protocol":"grpc","bind":"0.0.0.0:8090"}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an inst
ance of Promise
    at new NodeError (node:internal/errors:363:5)
    at write_ (node:_http_outgoing:740:11)
    at ServerResponse.end (node:_http_outgoing:853:5)
    at /home/depscloud/node_modules/express-prometheus-middleware/src/index.js:125:16
    at Layer.handle [as handle_request] (/home/depscloud/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/depscloud/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/depscloud/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/depscloud/node_modules/express/lib/router/layer.js:95:5)
    at /home/depscloud/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/depscloud/node_modules/express/lib/router/index.js:335:12)
    at next (/home/depscloud/node_modules/express/lib/router/index.js:275:10)
    at responseTime (/home/depscloud/node_modules/response-time/index.js:61:5)
    at Layer.handle [as handle_request] (/home/depscloud/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/depscloud/node_modules/express/lib/router/index.js:317:13)
    at /home/depscloud/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/depscloud/node_modules/express/lib/router/index.js:335:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

1. Pull extractor:0.3.2
2. issue request to the HTTP endpoint
3. inspect logs for error

**Expected behavior**
extractor should start up successfully.

**Comment by mjpitz** [comment]
Came across another issue with panics in the tracker process. This would likely only impact folks who run a read-only deployment (i.e. how I do api.deps.cloud). I really need to get some new integration tests in place... Some of these would have been caught by the old ones, but I wanted to change how they generally worked.

**Comment by mjpitz** [comment]
Resolving this as it appears to be resolved...
